name: DAGs Workflow

on:
  push:
    branches:
      - main
      - feat/**
    paths:
      - "airflow/dags/**"
  pull_request:
    branches:
      - main
    paths:
      - "airflow/dags/**"
  workflow_dispatch:

jobs:
  dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
      
      - name: Copy DAGs to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem -r airflow/dags/ ubuntu@${{ secrets.EC2_HOST }}:/opt/ecommerce-airflow/dags/
      
      - name: Restart Airflow services
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /opt/ecommerce-airflow
            sudo docker-compose restart airflow-webserver airflow-scheduler
          EOF